// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASy8BwZKPGuWmVfJGg5vXm1Rt_f9h_uu8',
    appId: '1:382952606812:android:458eedd372c3d7619faa99',
    messagingSenderId: '382952606812',
    projectId: 'otakutn-ca928',
    storageBucket: 'otakutn-ca928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtRSXXgAIxeA15hxYLNitsSfz-aJeGDy4',
    appId: '1:382952606812:ios:0151ab8e985c3be69faa99',
    messagingSenderId: '382952606812',
    projectId: 'otakutn-ca928',
    storageBucket: 'otakutn-ca928.firebasestorage.app',
    iosBundleId: 'com.example.otakutn',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQM9emKP5i9hjIes25hsqtrqBGljt4830',
    appId: '1:382952606812:web:2365b9c84b8e85bc9faa99',
    messagingSenderId: '382952606812',
    projectId: 'otakutn-ca928',
    authDomain: 'otakutn-ca928.firebaseapp.com',
    storageBucket: 'otakutn-ca928.firebasestorage.app',
    measurementId: 'G-CFRD237KKY',
  );
}